apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-app
  labels:
    app: apple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple-app
  template:
    metadata:
      labels:
        app: apple-app
    spec:
      containers:
      - name: apple-app
        image: hashicorp/http-echo
        args:
        - "-text=apple"